<?php

namespace AppBundle\Repository;

/**
 * ProductCategorieRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductCategorieRepository extends \Doctrine\ORM\EntityRepository
{
}
