<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * ProductRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ProductRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], [
            'id' => 'ASC'
        ]);
    }

    public function findByCategorie(array $criteria, array $orderBy = null, $limit = null, $offset = null)
    {
        $qb = $this->createQueryBuilder('p');
        $qb
            ->innerJoin('p.productCategorie', 'c')
            ->andWhere('c.name = :name')
            ->setParameter('name', $criteria['name'])
        ;

        return $qb->getQuery()->getResult();
    }
}
