app_bundle_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

app_bundle_shop:
    path: /shop
    defaults: { _controller: AppBundle:Default:shop }

app_bundle_shop_promotion:
    path: /promotion
    defaults: { _controller: AppBundle:Default:promotion }