app_bundle_homepage:
    path: /
    defaults: { _controller: AppBundle:Default:index }

app_bundle_shop:
    path: /products
    defaults: { _controller: AppBundle:Default:shop }

app_bundle_shop_promotion:
    path: /promotion
    defaults: { _controller: AppBundle:Default:promotion }

app_cart_add:
    path: /{id}/add
    defaults: { _controller: AppBundle:Cart:add}